version: '3.4'

services:
  web:
    build: ./
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:10.5
    restart: unless-stopped
    volumes:
#      - ./postgres_data:/var/lib/postgresql/data
      - ./postgresql/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=account_keeper
    ports:
      - 5432:5432
