# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_go_service_and_postgresql:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Start docker containers
      run: |
        bash run.sh

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Sleep for 10 seconds
      run: |
        sleep 10

    - name: Test with pytest
      run: |
        pytest

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
